/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Excepciones.Excepcion;
import UML.Alumno;
import UML.Asignatura;
import java.awt.Dialog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mikelferreiro.Main;

/**
 *
 * @author 1gprogexa13
 */
public class VConsulta extends javax.swing.JFrame {

    /**
     * Creates new form VConsulta
     */
    public VConsulta() {
        initComponents();
        setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbAsignatura = new javax.swing.JRadioButton();
        rbAlumno = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        bsalir = new javax.swing.JButton();
        bConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Consulta de profesores");

        bg.add(rbAsignatura);
        rbAsignatura.setText("Por asignatura");
        rbAsignatura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbAsignaturaItemStateChanged(evt);
            }
        });

        bg.add(rbAlumno);
        rbAlumno.setText("Por alumno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        bConsultar.setText("Consultar");
        bConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bsalir)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bConsultar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(rbAsignatura)
                            .addGap(52, 52, 52)
                            .addComponent(rbAlumno))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel2)
                            .addGap(32, 32, 32)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAlumno)
                    .addComponent(rbAsignatura))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(bsalir)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed
        try{
        if(rbAsignatura.isSelected() || rbAlumno.isSelected()){
            if(tfNombre.getText().isEmpty())
                throw new Excepcion(5);
            if(rbAsignatura.isSelected()){
                ArrayList<Alumno> alumnos=Main.buscarPorAsignatura(tfNombre.getText());
                if(alumnos.size()>0){
                rellenar1(alumnos);
                }else{
                    tfNombre.setText("");
                    throw new Excepcion(9);
                }
            }else{
                ArrayList<Asignatura> asignaturas=Main.buscarPorAlumno(tfNombre.getText());
                if(asignaturas.size()>0){
                rellenar2(asignaturas);
                }else{
                    tfNombre.setText("");
                    throw new Excepcion(9);
                }
            }
        }else{
            throw new Excepcion (8);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bConsultarActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        Main.cerrarJframe(this);
    }//GEN-LAST:event_bsalirActionPerformed

    private void rbAsignaturaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbAsignaturaItemStateChanged
        //pone los campos en blanco, basta con hacerlo en uno de los botones
        tfNombre.setText("");
        ta.setText("");
    }//GEN-LAST:event_rbAsignaturaItemStateChanged

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsultar;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton bsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAlumno;
    private javax.swing.JRadioButton rbAsignatura;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    private void rellenar1(ArrayList<Alumno> alumnos) {
        String texto="";
        for (int x=0;x<alumnos.size();x++){
            texto+=alumnos.get(x).getDni()+"   "+alumnos.get(x).getNombre()+"\n";
        }
        ta.setText(texto);
    }
    
    private void rellenar2(ArrayList<Asignatura> asignaturas) {
        String texto="";
        for (int x=0;x<asignaturas.size();x++){
            texto+=asignaturas.get(x).getNombre()+"\n";
        }
        ta.setText(texto);
    }
}
